services:
  - type: web
    name: dark-math-horizon-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:Maksat2007!@mekan.rzftzk0.mongodb.net/?retryWrites=true&w=majority&appName=Mekan
      - key: JWT_SECRET
        value: your-secret-key-here
      - key: PORT
        value: "5000"
      - key: CORS_ORIGIN
        value: https://grand-kitsune-290587.netlify.app
